version: '3.8'

services:
  service-discovery:
    build: ./service-discovery
    container_name: service-discovery
    ports:
      - "8761:8761"
    networks:
      - marketplace-network

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - service-discovery
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
    ports:
      - "8080:8080"
    networks:
      - marketplace-network

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - service-discovery
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/userdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
    ports:
      - "8082:8082"
    networks:
      - marketplace-network

  payment-service:
    build: ./payment-service
    container_name: payment-service
    depends_on:
      - service-discovery
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
    networks:
      - marketplace-network

  email-service:
    build: ./email-service
    container_name: email-service
    depends_on:
      - service-discovery
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
    networks:
      - marketplace-network

  product-service:
    build: ./product-service
    container_name: product-service
    depends_on:
      - service-discovery
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/productdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
    networks:
      - marketplace-network

  cart-service:
    build: ./cart-service
    container_name: cart-service
    depends_on:
      - service-discovery
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/cartdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery:8761/eureka
    networks:
      - marketplace-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - marketplace-network

volumes:
  pgdata:

networks:
  marketplace-network:
    driver: bridge