server:
  port: 8083

spring:
  application:
    name: cart-service
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

payment:
  stripe:
    secret-key: sk_test_your_stripe_secret_key_here
    success-url: http://localhost:8080/payment/success
    cancel-url: http://localhost:8080/payment/cancel